# Puerto del servidor
spring.application.name=ecommerce

# Configuración de la base de datos
server.port = 8085
spring.datasource.url = jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username = postgres
spring.datasource.password = picard

# Configuración del JPA para desarrollo
spring.jpa.hibernate.ddl-auto = update
spring.jpa.sql-show = true 
spring.jpa.database-plataform = org.hibernate.dialect.PostgreSQLDialect

